INSERT INTO transport_stop VALUES (0, '40 лет ВЛКСМ','Направление не указано', 0);
INSERT INTO transport_stop VALUES (1, '40 лет Октября','на Диагностический центр', 0);
INSERT INTO transport_stop VALUES (2, '40 лет Октября','на ст. Машиностроителей', 0);
INSERT INTO transport_stop VALUES (3, 'Автовокзал','на Фрунзе', 0);
INSERT INTO transport_stop VALUES (4, 'Автовокзал','на Южную', 0);
INSERT INTO transport_stop VALUES (5, 'Автомагистральная','на Пехотинцев', 0);
INSERT INTO transport_stop VALUES (6, 'Автомагистральная','на Сварщиков', 0);
INSERT INTO transport_stop VALUES (7, 'Академия при Президенте России','на Большакова', 0);
INSERT INTO transport_stop VALUES (8, 'Академия при Президенте России','на Цирк', 0);
INSERT INTO transport_stop VALUES (9, 'Бажова','на Восточную', 0);
INSERT INTO transport_stop VALUES (10, 'Бажова','на гост. Исеть, Оперный театр, Дом Кино', 0);
INSERT INTO transport_stop VALUES (11, 'Бакинских Комиссаров','на Уральских Рабочих', 0);
INSERT INTO transport_stop VALUES (12, 'Бакинских Комиссаров','на Победы', 0);
INSERT INTO transport_stop VALUES (13, 'Бебеля','на Пехотинцев', 0);
INSERT INTO transport_stop VALUES (14, 'Бебеля','на Таганский ряд', 0);
INSERT INTO transport_stop VALUES (15, 'Белинского','на Дом художника', 0);
INSERT INTO transport_stop VALUES (16, 'Белинского','на Цирк', 0);
INSERT INTO transport_stop VALUES (17, 'Белореченская','на Волгоградскую', 0);
INSERT INTO transport_stop VALUES (18, 'Белореченская','на Московскую', 0);
INSERT INTO transport_stop VALUES (19, 'Библиотека','на Донбасскую', 0);
INSERT INTO transport_stop VALUES (20, 'Библиотека','на Лукиных', 0);
INSERT INTO transport_stop VALUES (21, 'Блюхера','на ст.Шарташ', 0);
INSERT INTO transport_stop VALUES (22, 'Блюхера','с Мира на Уральский федеральный университет', 0);
INSERT INTO transport_stop VALUES (23, 'Блюхера','с Советской на Уральский федеральный университет', 0);
INSERT INTO transport_stop VALUES (24, 'Блюхера','на Пионерскую', 0);
INSERT INTO transport_stop VALUES (25, 'Большакова','на Академию при Президенте России', 0);
INSERT INTO transport_stop VALUES (26, 'Большакова','на Фрунзе', 0);
INSERT INTO transport_stop VALUES (27, 'Б-р Малахова','на Фучика', 0);
INSERT INTO transport_stop VALUES (28, 'Б-р Малахова','на ст. м. Ботаническая', 0);
INSERT INTO transport_stop VALUES (29, 'Братская','на Сухоложскую', 0);
INSERT INTO transport_stop VALUES (30, 'Братская','на Завод РТИ', 0);
INSERT INTO transport_stop VALUES (31, 'Ватутина','на ст. 7 Ключей', 0);
INSERT INTO transport_stop VALUES (32, 'Ватутина','на Таганский ряд', 0);
INSERT INTO transport_stop VALUES (33, 'Верх-Исетский б-р','на Крылова', 0);
INSERT INTO transport_stop VALUES (34, 'Верх-Исетский б-р','на Дворец Молодежи', 0);
INSERT INTO transport_stop VALUES (35, 'Верх-Исетский рынок','на Таганский ряд', 0);
INSERT INTO transport_stop VALUES (36, 'Верх-Исетский рынок','на Колмогорова', 0);
INSERT INTO transport_stop VALUES (37, 'Вечный Огонь','на Мельникова', 0);
INSERT INTO transport_stop VALUES (38, 'Вечный Огонь','на пл. Коммунаров', 0);
INSERT INTO transport_stop VALUES (39, 'ВИЗ','Направление не указано', 0);
INSERT INTO transport_stop VALUES (40, 'Викулова','на Волгоградскую', 0);
INSERT INTO transport_stop VALUES (41, 'Викулова','на ст. ВИЗ', 0);
INSERT INTO transport_stop VALUES (42, 'Войкова','на ст. Фрезеровщиков', 0);
INSERT INTO transport_stop VALUES (43, 'Войкова','на Энтузиастов', 0);
INSERT INTO transport_stop VALUES (44, 'Волгоградская','Направление не указано', 0);
INSERT INTO transport_stop VALUES (45, 'Волгоградская','на ТК Буревестник', 0);
INSERT INTO transport_stop VALUES (46, 'Волгоградская','на Серафимы Дерябиной', 0);
INSERT INTO transport_stop VALUES (47, 'Ворошиловская','на Фронтовых Бригад', 0);
INSERT INTO transport_stop VALUES (48, 'Ворошиловская','на Электриков', 0);
INSERT INTO transport_stop VALUES (49, 'Восточная','на Уральский федеральный университет', 0);
INSERT INTO transport_stop VALUES (50, 'Восточная','на Бажова', 0);
INSERT INTO transport_stop VALUES (51, 'Вторчермет','Направление не указано', 0);
INSERT INTO transport_stop VALUES (52, 'Гагарина','на Профессорскую', 0);
INSERT INTO transport_stop VALUES (53, 'Гагарина','на Уральский федеральный университет', 0);
INSERT INTO transport_stop VALUES (54, 'Гост. Исеть','на Шарташскую', 0);
INSERT INTO transport_stop VALUES (55, 'Гост. Исеть','на Бажова, Дом Кино, Оперный театр', 0);
INSERT INTO transport_stop VALUES (56, 'Гурзуфская','на Волгоградскую', 0);
INSERT INTO transport_stop VALUES (57, 'Гурзуфская','на Московскую', 0);
INSERT INTO transport_stop VALUES (58, 'Дворец Молодежи','на Верх-Исетский б-р', 0);
INSERT INTO transport_stop VALUES (59, 'Дворец Молодежи','на пл.Коммунаров, Шейнкмана', 0);
INSERT INTO transport_stop VALUES (60, 'Дворец Спорта','Направление не указано', 0);
INSERT INTO transport_stop VALUES (61, 'Декабристов','на Дом художника', 0);
INSERT INTO transport_stop VALUES (62, 'Декабристов','на пл. Обороны', 0);
INSERT INTO transport_stop VALUES (63, 'Диагностический центр','на 40 лет Октября', 0);
INSERT INTO transport_stop VALUES (64, 'Диагностический центр','на Лукиных', 0);
INSERT INTO transport_stop VALUES (65, 'ДК ВОС','на ст. 7 Ключей', 0);
INSERT INTO transport_stop VALUES (66, 'ДК ВОС','на Таганский ряд', 0);
INSERT INTO transport_stop VALUES (67, 'ДК им. Лаврова','на Ильича', 0);
INSERT INTO transport_stop VALUES (68, 'ДК им. Лаврова','на Кузнецова', 0);
INSERT INTO transport_stop VALUES (69, 'Дом Кино','на Киностудию', 0);
INSERT INTO transport_stop VALUES (70, 'Дом Кино','на Дом художника', 0);
INSERT INTO transport_stop VALUES (71, 'Дом художника','на Дом Кино', 0);
INSERT INTO transport_stop VALUES (72, 'Дом художника','на Декабристов', 0);
INSERT INTO transport_stop VALUES (73, 'Дом художника','с Декабристов на Цирк', 0);
INSERT INTO transport_stop VALUES (74, 'Дом художника','с Дома Кино на Цирк', 0);
INSERT INTO transport_stop VALUES (75, 'Донбасская','на Кировградскую', 0);
INSERT INTO transport_stop VALUES (76, 'Донбасская','на Библиотеку', 0);
INSERT INTO transport_stop VALUES (77, 'Донская','на ст. Эльмаш', 0);
INSERT INTO transport_stop VALUES (78, 'Донская','на Энтузиастов', 0);
INSERT INTO transport_stop VALUES (79, 'Дружининская','на Таганский ряд', 0);
INSERT INTO transport_stop VALUES (80, 'Дружининская','на ст. 7 Ключей', 0);
INSERT INTO transport_stop VALUES (81, 'ЖД вокзал','на Управление дороги', 0);
INSERT INTO transport_stop VALUES (82, 'ЖД вокзал','на Челюскинцев, Пионерскую', 0);
INSERT INTO transport_stop VALUES (83, 'Завод РТИ','на Братскую', 0);
INSERT INTO transport_stop VALUES (84, 'Завод РТИ','на пер. Рижский', 0);
INSERT INTO transport_stop VALUES (85, 'Заводская','на Красноуральскую', 0);
INSERT INTO transport_stop VALUES (86, 'Заводская','на Татищева', 0);
INSERT INTO transport_stop VALUES (87, 'Зеленый остров','Направление не указано', 0);
INSERT INTO transport_stop VALUES (88, 'Ильича','на ДК им. Лаврова', 0);
INSERT INTO transport_stop VALUES (89, 'Ильича','на Индустрии', 0);
INSERT INTO transport_stop VALUES (90, 'Индустрии','на Ильича', 0);
INSERT INTO transport_stop VALUES (91, 'Индустрии','на Победы', 0);
INSERT INTO transport_stop VALUES (92, 'Калининская','на Педагогический университет', 0);
INSERT INTO transport_stop VALUES (93, 'Калининская','на Техучилище', 0);
INSERT INTO transport_stop VALUES (94, 'Каменные Палатки','на Комсомольскую', 0);
INSERT INTO transport_stop VALUES (95, 'Каменные Палатки','на Новгородцевой', 0);
INSERT INTO transport_stop VALUES (96, 'Керамическая','Направление не указано', 0);
INSERT INTO transport_stop VALUES (97, 'Киностудия','на Бажова, гост. Исеть, Оперный театр', 0);
INSERT INTO transport_stop VALUES (98, 'Кирова','на Крылова', 0);
INSERT INTO transport_stop VALUES (99, 'Кирова','на ст. ВИЗ', 0);
INSERT INTO transport_stop VALUES (100, 'Кирова','на Колмогорова', 0);
INSERT INTO transport_stop VALUES (101, 'Кировградская','на Донбасскую', 0);
INSERT INTO transport_stop VALUES (102, 'Кировградская','на Уральских Рабочих', 0);
INSERT INTO transport_stop VALUES (103, 'Кишиневская','на Таганский ряд', 0);
INSERT INTO transport_stop VALUES (104, 'Кишиневская','на ст. 7 Ключей', 0);
INSERT INTO transport_stop VALUES (105, 'Колмогорова','на Таганский ряд', 0);
INSERT INTO transport_stop VALUES (106, 'Колмогорова','на Кирова', 0);
INSERT INTO transport_stop VALUES (107, 'Комсомольская','на Профессорскую', 0);
INSERT INTO transport_stop VALUES (108, 'Комсомольская','на ст. 40 лет ВЛКСМ', 0);
INSERT INTO transport_stop VALUES (109, 'Кондукторская','на Пионерскую', 0);
INSERT INTO transport_stop VALUES (110, 'Кондукторская','на Блюхера', 0);
INSERT INTO transport_stop VALUES (111, 'Красноуральская','на Заводскую', 0);
INSERT INTO transport_stop VALUES (112, 'Красноуральская','на Слесарей', 0);
INSERT INTO transport_stop VALUES (113, 'Красноуральская','на Уралкабель', 0);
INSERT INTO transport_stop VALUES (114, 'Краснофлотцев','на Фронтовых Бригад', 0);
INSERT INTO transport_stop VALUES (115, 'Краснофлотцев','на Энтузиастов', 0);
INSERT INTO transport_stop VALUES (116, 'Крылова','на Верх-Исетский б-р', 0);
INSERT INTO transport_stop VALUES (117, 'Крылова','на Кирова', 0);
INSERT INTO transport_stop VALUES (118, 'Кузнецова','с ДК им. Лаврова на ст. пл. 1-й Пятилетки', 0);
INSERT INTO transport_stop VALUES (119, 'Кузнецова','с м. Уралмаш на ст. пл. 1-й Пятилетки', 0);
INSERT INTO transport_stop VALUES (120, 'Кузнецова','на ДК им. Лаврова', 0);
INSERT INTO transport_stop VALUES (121, 'Кузнецова','на м. Уралмаш', 0);
INSERT INTO transport_stop VALUES (122, 'Куйбышева','на Цирк, пл. Коммунаров', 0);
INSERT INTO transport_stop VALUES (123, 'Куйбышева','на ст. Дворец Спорта', 0);
INSERT INTO transport_stop VALUES (124, 'Кушвинская','Направление не указано', 0);
INSERT INTO transport_stop VALUES (125, 'Лукиных','на  Библиотеку', 0);
INSERT INTO transport_stop VALUES (126, 'Лукиных','на Диагностический центр', 0);
INSERT INTO transport_stop VALUES (127, 'Лукиных','на Сварщиков', 0);
INSERT INTO transport_stop VALUES (128, 'Ляпустина','на ст. Керамическая', 0);
INSERT INTO transport_stop VALUES (129, 'Ляпустина','на Ферганскую', 0);
INSERT INTO transport_stop VALUES (130, 'М. Ботаническая','Направление не указано', 0);
INSERT INTO transport_stop VALUES (131, 'М. Уралмаш','на Кузнецова', 0);
INSERT INTO transport_stop VALUES (132, 'М. Уралмаш','на Педагогический университет', 0);
INSERT INTO transport_stop VALUES (133, 'Малый конный','на ст. Зеленый остров', 0);
INSERT INTO transport_stop VALUES (134, 'Малый конный','на ст. ВИЗ', 0);
INSERT INTO transport_stop VALUES (135, 'Маневровая','на ст. 7 Ключей', 0);
INSERT INTO transport_stop VALUES (136, 'Маневровая','на Таганский ряд', 0);
INSERT INTO transport_stop VALUES (137, 'Машиностроителей','Направление не указано', 0);
INSERT INTO transport_stop VALUES (138, 'Мельникова','на Уралкабель', 0);
INSERT INTO transport_stop VALUES (139, 'Мельникова','на Вечный Огонь', 0);
INSERT INTO transport_stop VALUES (140, 'Металлургов','на ст. ВИЗ', 0);
INSERT INTO transport_stop VALUES (141, 'Металлургов','на Волгоградскую', 0);
INSERT INTO transport_stop VALUES (142, 'Мира','на Блюхера', 0);
INSERT INTO transport_stop VALUES (143, 'Мира','на ТК Современник', 0);
INSERT INTO transport_stop VALUES (144, 'Московская','на ст. Дворец Спорта', 0);
INSERT INTO transport_stop VALUES (145, 'Московская','на ТК Алатырь', 0);
INSERT INTO transport_stop VALUES (146, 'Московская','на Юго-Западную', 0);
INSERT INTO transport_stop VALUES (147, 'Московская','с ТК Алатырь на Цирк', 0);
INSERT INTO transport_stop VALUES (148, 'Московская','с Юго-Западной на Цирк', 0);
INSERT INTO transport_stop VALUES (149, 'Московская от ст. Дворец Спорта','со ст. Дворец Спорта на Цирк', 0);
INSERT INTO transport_stop VALUES (150, 'Мусоргского','на ст. Керамическая', 0);
INSERT INTO transport_stop VALUES (151, 'Мусоргского','на Эскадронную', 0);
INSERT INTO transport_stop VALUES (152, 'Новгородцевой','на Каменные палатки', 0);
INSERT INTO transport_stop VALUES (153, 'Новгородцевой','на Сиреневый б-р', 0);
INSERT INTO transport_stop VALUES (154, 'Новомосковская','на ст. ВИЗ', 0);
INSERT INTO transport_stop VALUES (155, 'Новомосковская','на Волгоградскую', 0);
INSERT INTO transport_stop VALUES (156, 'Новосибирская','на ст. Керамическая', 0);
INSERT INTO transport_stop VALUES (157, 'Новосибирская','на Ляпустина', 0);
INSERT INTO transport_stop VALUES (158, 'Оперный театр','на пл. 1905 года', 0);
INSERT INTO transport_stop VALUES (159, 'Оперный театр','на гост. Исеть, Бажова,  Дом Кино', 0);
INSERT INTO transport_stop VALUES (160, 'Папанина','на Шейнкмана', 0);
INSERT INTO transport_stop VALUES (161, 'Папанина','на Управление дороги', 0);
INSERT INTO transport_stop VALUES (162, 'Педагогический университет','на м. Уралмаш', 0);
INSERT INTO transport_stop VALUES (163, 'Педагогический университет','на Пионерскую', 0);
INSERT INTO transport_stop VALUES (164, 'Педагогический университет','на Электриков', 0);
INSERT INTO transport_stop VALUES (165, 'Педагогический университет','с Электриков на Пионерскую', 0);
INSERT INTO transport_stop VALUES (166, 'Пер. Рижский','на Завод РТИ', 0);
INSERT INTO transport_stop VALUES (167, 'Пер. Рижский','на Ювелирную', 0);
INSERT INTO transport_stop VALUES (168, 'Первомайская','на Блюхера', 0);
INSERT INTO transport_stop VALUES (169, 'Первомайская','на Уральский федеральный университет', 0);
INSERT INTO transport_stop VALUES (170, 'Пехотинцев','на Автомагистральную', 0);
INSERT INTO transport_stop VALUES (171, 'Пехотинцев','на Бебеля', 0);
INSERT INTO transport_stop VALUES (172, 'Пионерская','на 1-й км', 0);
INSERT INTO transport_stop VALUES (173, 'Пионерская','с 1-го км на Челюскинцев, ЖД вокзал', 0);
INSERT INTO transport_stop VALUES (174, 'Пионерская','с Кондукторской на Челюскинцев, ЖД вокзал', 0);
INSERT INTO transport_stop VALUES (175, 'Пионерская','на Кондукторскую', 0);
INSERT INTO transport_stop VALUES (176, 'Пл. 1905 г.','на гост. Исеть', 0);
INSERT INTO transport_stop VALUES (177, 'Пл. 1905 г.','на пл. Коммунаров', 0);
INSERT INTO transport_stop VALUES (178, 'Пл. 1-й Пятилетки','Направление не указано', 0);
INSERT INTO transport_stop VALUES (179, 'Пл. 1-й Пятилетки','на ст. пл. 1-й Пятилетки', 0);
INSERT INTO transport_stop VALUES (180, 'Пл. Коммунаров','на ТК Алатырь', 0);
INSERT INTO transport_stop VALUES (181, 'Пл. Коммунаров','с ТК Алатырь на Дворец Молодежи', 0);
INSERT INTO transport_stop VALUES (182, 'Пл. Коммунаров','на пл. 1905 г.', 0);
INSERT INTO transport_stop VALUES (183, 'Пл. Коммунаров','на Вечный Огонь', 0);
INSERT INTO transport_stop VALUES (184, 'Пл. Обороны','на Декабристов', 0);
INSERT INTO transport_stop VALUES (185, 'Пл. Обороны','на Тверитина', 0);
INSERT INTO transport_stop VALUES (186, 'Плотников','со ст. Зеленый остров на ст. ВИЗ', 0);
INSERT INTO transport_stop VALUES (187, 'Плотников','на ст. Зеленый остров', 0);
INSERT INTO transport_stop VALUES (188, 'Плотников','на Волгоградскую', 0);
INSERT INTO transport_stop VALUES (189, 'Плотников','с Волгоградской на Металлургов', 0);
INSERT INTO transport_stop VALUES (190, 'Победы','на Индустрии', 0);
INSERT INTO transport_stop VALUES (191, 'Победы','на Бакинских Комиссаров', 0);
INSERT INTO transport_stop VALUES (192, 'Посадская','на Цирк, пл. Коммунаров', 0);
INSERT INTO transport_stop VALUES (193, 'Посадская','на ст. Дворец Спорта', 0);
INSERT INTO transport_stop VALUES (194, 'Протезно-ортопедическое предприятие','на Челюскинцев', 0);
INSERT INTO transport_stop VALUES (195, 'Протезно-ортопедическое предприятие','на Шевченко', 0);
INSERT INTO transport_stop VALUES (196, 'Профессорская','на Гагарина', 0);
INSERT INTO transport_stop VALUES (197, 'Профессорская','на Комсомольскую', 0);
INSERT INTO transport_stop VALUES (198, 'Рабочих','на ст. Зеленый остров', 0);
INSERT INTO transport_stop VALUES (199, 'Рабочих','на ст. ВИЗ', 0);
INSERT INTO transport_stop VALUES (200, 'Радищева','на Московскую', 0);
INSERT INTO transport_stop VALUES (201, 'Радищева','на Цирк', 0);
INSERT INTO transport_stop VALUES (202, 'Разъезд','на ст. Зеленый остров', 0);
INSERT INTO transport_stop VALUES (203, 'Разъезд','на ст. ВИЗ', 0);
INSERT INTO transport_stop VALUES (204, 'Расточная','на ст. 7 Ключей', 0);
INSERT INTO transport_stop VALUES (205, 'Расточная','на Таганский ряд', 0);
INSERT INTO transport_stop VALUES (206, 'Сакко и Ванцетти','на пл. Коммунаров', 0);
INSERT INTO transport_stop VALUES (207, 'Сахалинская','на Студенческую', 0);
INSERT INTO transport_stop VALUES (208, 'Сахалинская','на ст. Шарташ', 0);
INSERT INTO transport_stop VALUES (209, 'Сварщиков','на Автомагистральную', 0);
INSERT INTO transport_stop VALUES (210, 'Сварщиков','на Лукиных', 0);
INSERT INTO transport_stop VALUES (211, 'Серафимы Дерябиной','на ст. ВИЗ', 0);
INSERT INTO transport_stop VALUES (212, 'Серафимы Дерябиной','на Волгоградскую', 0);
INSERT INTO transport_stop VALUES (213, 'Сиреневый б-р','на ст. 40 лет ВЛКСМ', 0);
INSERT INTO transport_stop VALUES (214, 'Сиреневый б-р','на Новгородцевой', 0);
INSERT INTO transport_stop VALUES (215, 'Слесарей','на ст. ВИЗ, Кирова', 0);
INSERT INTO transport_stop VALUES (216, 'Советская','на Пионерскую', 0);
INSERT INTO transport_stop VALUES (217, 'Советская','на Блюхера', 0);
INSERT INTO transport_stop VALUES (218, 'Студенческая','на ТК Современник', 0);
INSERT INTO transport_stop VALUES (219, 'Студенческая','на Сахалинскую', 0);
INSERT INTO transport_stop VALUES (220, 'Сухоложская','на ст. Вторчермет, ст. Керамическая', 0);
INSERT INTO transport_stop VALUES (221, 'Сухоложская','на Братскую', 0);
INSERT INTO transport_stop VALUES (222, 'Таганский ряд','со ст. 7 Ключей на Лукиных', 0);
INSERT INTO transport_stop VALUES (223, 'Таганский ряд','на ст. 7 Ключей', 0);
INSERT INTO transport_stop VALUES (224, 'Таганский ряд','с  ТРЦ Карнавал на Лукиных', 0);
INSERT INTO transport_stop VALUES (225, 'Таганский ряд','на ТРЦ Карнавал', 0);
INSERT INTO transport_stop VALUES (226, 'Татищева','на Заводскую', 0);
INSERT INTO transport_stop VALUES (227, 'Татищева','на Волгоградскую, ст. Зеленый остров', 0);
INSERT INTO transport_stop VALUES (228, 'Тверитина','на ст. ЦПКиО', 0);
INSERT INTO transport_stop VALUES (229, 'Тверитина','на Куйбышева-Луначарского', 0);
INSERT INTO transport_stop VALUES (230, 'Театр музыкальной комедии','на Оперный театр', 0);
INSERT INTO transport_stop VALUES (231, 'Театр музыкальной комедии','на пл. 1905 г.', 0);
INSERT INTO transport_stop VALUES (232, 'Теплоходный  пр.','на ст. 7 Ключей', 0);
INSERT INTO transport_stop VALUES (233, 'Теплоходный пр.','на Таганский ряд', 0);
INSERT INTO transport_stop VALUES (234, 'Техническая','на ст. 7 Ключей', 0);
INSERT INTO transport_stop VALUES (235, 'Техническая','на Таганский ряд', 0);
INSERT INTO transport_stop VALUES (236, 'Техучилище','на 1-й км', 0);
INSERT INTO transport_stop VALUES (237, 'Техучилище','на Калининскую', 0);
INSERT INTO transport_stop VALUES (238, 'ТК Буревестник','на Волгоградскую', 0);
INSERT INTO transport_stop VALUES (239, 'ТК Буревестник','на Московскую', 0);
INSERT INTO transport_stop VALUES (240, 'ТК Современник','на Мира', 0);
INSERT INTO transport_stop VALUES (241, 'ТК Современник','на Студенческую', 0);
INSERT INTO transport_stop VALUES (242, 'ТРЦ Карнавал','на Верх-Исетский рынок', 0);
INSERT INTO transport_stop VALUES (243, 'ТРЦ Карнавал','на Таганский ряд', 0);
INSERT INTO transport_stop VALUES (244, 'ТЦ Алатырь','на Московскую', 0);
INSERT INTO transport_stop VALUES (245, 'ТЦ Алатырь','на пл. Коммунаров', 0);
INSERT INTO transport_stop VALUES (246, 'Управление дороги','на Ельцина', 0);
INSERT INTO transport_stop VALUES (247, 'Управление дороги','на ЖД вокзал', 0);
INSERT INTO transport_stop VALUES (248, 'Уралкабель','на Красноуральскую', 0);
INSERT INTO transport_stop VALUES (249, 'Уралкабель','на Мельникова', 0);
INSERT INTO transport_stop VALUES (250, 'Уральский федеральный университет','на Восточную', 0);
INSERT INTO transport_stop VALUES (251, 'Уральский федеральный университет','на Первомайскую', 0);
INSERT INTO transport_stop VALUES (252, 'Уральский федеральный университет','на Профессорскую', 0);
INSERT INTO transport_stop VALUES (253, 'Уральских Рабочих','на Бакинских Комиссаров', 0);
INSERT INTO transport_stop VALUES (254, 'Уральских Рабочих','на Кировградскую', 0);
INSERT INTO transport_stop VALUES (255, 'Ухтомская','на Серафимы Дерябиной', 0);
INSERT INTO transport_stop VALUES (256, 'Ухтомская','на ст. ВИЗ', 0);
INSERT INTO transport_stop VALUES (257, 'Учителей','на Кондукторскую', 0);
INSERT INTO transport_stop VALUES (258, 'Учителей','на Блюхера', 0);
INSERT INTO transport_stop VALUES (259, 'Фармацевтический колледж','на ТРЦ Карнавал', 0);
INSERT INTO transport_stop VALUES (260, 'Фармацевтический колледж','на Таганский ряд', 0);
INSERT INTO transport_stop VALUES (261, 'Ферганская','на Сухоложскую', 0);
INSERT INTO transport_stop VALUES (262, 'Ферганская','на ст. Керамическая', 0);
INSERT INTO transport_stop VALUES (263, 'Фрезеровщиков','Направление не указано', 0);
INSERT INTO transport_stop VALUES (264, 'Фронтовых Бригад','на Ворошиловскую', 0);
INSERT INTO transport_stop VALUES (265, 'Фронтовых Бригад','на Краснофлотцев', 0);
INSERT INTO transport_stop VALUES (266, 'Фрунзе','на Автовокзал', 0);
INSERT INTO transport_stop VALUES (267, 'Фрунзе','на Большакова', 0);
INSERT INTO transport_stop VALUES (268, 'Фучика','на Южную, Шварца', 0);
INSERT INTO transport_stop VALUES (269, 'Фучика','на б-р Малахова', 0);
INSERT INTO transport_stop VALUES (270, 'Цирк','на Белинского', 0);
INSERT INTO transport_stop VALUES (271, 'Цирк','на Академию при Президенте России', 0);
INSERT INTO transport_stop VALUES (272, 'Цирк','с Белинского на Радищева', 0);
INSERT INTO transport_stop VALUES (273, 'Цирк','с Академии при Президенте России на Радищева', 0);
INSERT INTO transport_stop VALUES (274, 'ЦПКиО','Направление не указано', 0);
INSERT INTO transport_stop VALUES (275, 'Челюскинцев','на ЖД вокзал, Пионерскую', 0);
INSERT INTO transport_stop VALUES (276, 'Челюскинцев','на Протезно-ортопедическое предприятие', 0);
INSERT INTO transport_stop VALUES (277, 'Шарташ','Направление не указано', 0);
INSERT INTO transport_stop VALUES (278, 'Шарташская','на гост. Исеть', 0);
INSERT INTO transport_stop VALUES (279, 'Шарташская','на Шевченко', 0);
INSERT INTO transport_stop VALUES (280, 'Шевченко','на Протезно-ортопедическое предприятие', 0);
INSERT INTO transport_stop VALUES (281, 'Шевченко','на Шарташскую', 0);
INSERT INTO transport_stop VALUES (282, 'Шейнкмана','на Дворец Молодежи', 0);
INSERT INTO transport_stop VALUES (283, 'Шейнкмана','на Папанина', 0);
INSERT INTO transport_stop VALUES (284, 'Школа им. С.В. Рахманинова','на ст. 7 Ключей', 0);
INSERT INTO transport_stop VALUES (285, 'Школа им. С.В. Рахманинова','на Таганский ряд', 0);
INSERT INTO transport_stop VALUES (286, 'Электриков','на Ворошиловскую', 0);
INSERT INTO transport_stop VALUES (287, 'Электриков','на Педагогический университет', 0);
INSERT INTO transport_stop VALUES (288, 'Эльмаш','Направление не указано', 0);
INSERT INTO transport_stop VALUES (289, 'Энтузиастов','с Краснофлотцев на ст. Эльмаш, ст. Фрезеровщиков', 0);
INSERT INTO transport_stop VALUES (290, 'Энтузиастов','со ст. Фрезеровщиков на Краснофлотцев', 0);
INSERT INTO transport_stop VALUES (291, 'Энтузиастов','со ст. Эльмаш на Краснофлотцев', 0);
INSERT INTO transport_stop VALUES (292, 'Эскадронная','на ст. Керамическая', 0);
INSERT INTO transport_stop VALUES (293, 'Эскадронная','на Ляпустина', 0);
INSERT INTO transport_stop VALUES (294, 'Ювелирная','на Шварца', 0);
INSERT INTO transport_stop VALUES (295, 'Ювелирная','на пер. Рижский', 0);
INSERT INTO transport_stop VALUES (296, 'Юго-Западная','на Белореченскую', 0);
INSERT INTO transport_stop VALUES (297, 'Юго-Западная','на Московскую', 0);
INSERT INTO transport_stop VALUES (298, 'Южная','на Автовокзал', 0);
INSERT INTO transport_stop VALUES (299, 'Южная','на Шварца, Фучика', 0);
INSERT INTO transport_stop VALUES (300, 'Южная','конечная', 0);
INSERT INTO transport_stop VALUES (301, '40 лет Октября','на Хмелева', 1);
INSERT INTO transport_stop VALUES (302, 'Авиационная','на Саввы Белых', 1);
INSERT INTO transport_stop VALUES (303, 'Авиационная','на Щорса', 1);
INSERT INTO transport_stop VALUES (304, 'Автовокзал','на Серова', 1);
INSERT INTO transport_stop VALUES (305, 'Автовокзал','на Щорса', 1);
INSERT INTO transport_stop VALUES (306, 'Азина','на Дом Музыки', 1);
INSERT INTO transport_stop VALUES (307, 'Академгородок','Направление не указано', 1);
INSERT INTO transport_stop VALUES (308, 'Академика Вонсовского','на Начдива Онуфриева', 1);
INSERT INTO transport_stop VALUES (309, 'Академика Вонсовского','на Рабочую', 1);
INSERT INTO transport_stop VALUES (310, 'Академическая','на Мира', 1);
INSERT INTO transport_stop VALUES (311, 'Академическая','Направление не указано', 1);
INSERT INTO transport_stop VALUES (312, 'Академическая','на ТК Современник', 1);
INSERT INTO transport_stop VALUES (313, 'Амундсена','на Начдива Онуфриева', 1);
INSERT INTO transport_stop VALUES (314, 'Амундсена','на Волгоградскую', 1);
INSERT INTO transport_stop VALUES (315, 'Амундсена','на пр-д Решетникова', 1);
INSERT INTO transport_stop VALUES (316, 'Артиллерийский институт','на Прониной', 1);
INSERT INTO transport_stop VALUES (317, 'Артиллерийский институт','на Садовую', 1);
INSERT INTO transport_stop VALUES (318, 'Архитектурная академия','на ТЮЗ', 1);
INSERT INTO transport_stop VALUES (319, 'Архитектурная академия','на пр. Ленина', 1);
INSERT INTO transport_stop VALUES (320, 'Бакинских Комиссаров','на Ломоносова', 1);
INSERT INTO transport_stop VALUES (321, 'Бакинских Комиссаров','на ст. Коммунистическая', 1);
INSERT INTO transport_stop VALUES (322, 'Баумана','на Красных Командиров', 1);
INSERT INTO transport_stop VALUES (323, 'Белореченская','на ст. Посадская', 1);
INSERT INTO transport_stop VALUES (324, 'Белореченская','на Гурзуфскую', 1);
INSERT INTO transport_stop VALUES (325, 'Библиотека','на Краснознаменную', 1);
INSERT INTO transport_stop VALUES (326, 'Библиотека им. Белинского','на Дом Кино, пр. Ленина', 1);
INSERT INTO transport_stop VALUES (327, 'Библиотека им. Крапивина','на Советскую', 1);
INSERT INTO transport_stop VALUES (328, 'Библиотека им. Крапивина','на Луначарского', 1);
INSERT INTO transport_stop VALUES (329, 'Большакова','на Декабристов', 1);
INSERT INTO transport_stop VALUES (330, 'Боровая','на ТК Современник', 1);
INSERT INTO transport_stop VALUES (331, 'Боровая','на Менделеева', 1);
INSERT INTO transport_stop VALUES (332, 'Бородина','на Инженерную', 1);
INSERT INTO transport_stop VALUES (333, 'Бородина','на ДК Химмаш', 1);
INSERT INTO transport_stop VALUES (334, 'Ботаническая','Направление не указано', 1);
INSERT INTO transport_stop VALUES (335, 'Б-р Культуры','на пр. Орджоникидзе', 1);
INSERT INTO transport_stop VALUES (336, 'Б-р Малахова','на ст. Ботаническая', 1);
INSERT INTO transport_stop VALUES (337, 'Б-р Малахова','на Тбилисский б-р', 1);
INSERT INTO transport_stop VALUES (338, 'Веер','на Ломоносова', 1);
INSERT INTO transport_stop VALUES (339, 'Веер','на Ярославскую', 1);
INSERT INTO transport_stop VALUES (340, 'Викулова','на Крауля', 1);
INSERT INTO transport_stop VALUES (341, 'Викулова','на Заводскую', 1);
INSERT INTO transport_stop VALUES (342, 'Войкова','на Красных Командиров', 1);
INSERT INTO transport_stop VALUES (343, 'Волгоградская','на Амундсена', 1);
INSERT INTO transport_stop VALUES (344, 'Волгоградская','на Шаумяна', 1);
INSERT INTO transport_stop VALUES (345, 'Ворошиловская','на Фронтовых Бригад', 1);
INSERT INTO transport_stop VALUES (346, 'Ворошиловская','на Электриков', 1);
INSERT INTO transport_stop VALUES (347, 'Восстания','на Стахановскую', 1);
INSERT INTO transport_stop VALUES (348, 'Восстания','на Ломоносова', 1);
INSERT INTO transport_stop VALUES (349, 'Восстания','на Победы', 1);
INSERT INTO transport_stop VALUES (350, 'Гагарина','на Генеральскую', 1);
INSERT INTO transport_stop VALUES (351, 'Гагарина','на Профессорскую', 1);
INSERT INTO transport_stop VALUES (352, 'Генеральская','на Трансагентство', 1);
INSERT INTO transport_stop VALUES (353, 'Генеральская','на Гагарина', 1);
INSERT INTO transport_stop VALUES (354, 'Гончарный','на Уктус', 1);
INSERT INTO transport_stop VALUES (355, 'Горького','на Храм Большой Златоуст', 1);
INSERT INTO transport_stop VALUES (356, 'Гурзуфская','на Белореченскую', 1);
INSERT INTO transport_stop VALUES (357, 'Гурзуфская','на Репина', 1);
INSERT INTO transport_stop VALUES (358, 'Дагестанская','на ст. Химмаш', 1);
INSERT INTO transport_stop VALUES (359, 'Данилы Зверева','на Боровую', 1);
INSERT INTO transport_stop VALUES (360, 'Декабристов','на Куйбышева', 1);
INSERT INTO transport_stop VALUES (361, 'Декабристов','с Большакова на Чапаева', 1);
INSERT INTO transport_stop VALUES (362, 'Детская больница','на пл. 1-й Пятилетки', 1);
INSERT INTO transport_stop VALUES (363, 'Димитрова','на Косарева', 1);
INSERT INTO transport_stop VALUES (364, 'ДК железнодорожников','на ст. ЖД вокзал, ст. Академическая, ст. Коммунистическая', 1);
INSERT INTO transport_stop VALUES (365, 'ДК им. Лаврова','на Фрезеровщиков', 1);
INSERT INTO transport_stop VALUES (366, 'ДК им. Лаврова','на м. Уралмаш', 1);
INSERT INTO transport_stop VALUES (367, 'ДК Химмаш','на Бородина', 1);
INSERT INTO transport_stop VALUES (368, 'ДК Химмаш','на Димитрова', 1);
INSERT INTO transport_stop VALUES (369, 'Дом Кино','на Горького, ст. ЖД вокзал, ст. Химмаш', 1);
INSERT INTO transport_stop VALUES (370, 'Дом Кино','на Трансагентство', 1);
INSERT INTO transport_stop VALUES (371, 'Дом Музыки','на ДК железнодорожников', 1);
INSERT INTO transport_stop VALUES (372, 'Дом Музыки','на ТЮЗ', 1);
INSERT INTO transport_stop VALUES (373, 'Дом Пионеров','на пр. Орджоникидзе', 1);
INSERT INTO transport_stop VALUES (374, 'ЖД вокзал','на Азина', 1);
INSERT INTO transport_stop VALUES (375, 'ЖД вокзал','1, 9 маршруты', 1);
INSERT INTO transport_stop VALUES (376, 'ЖД вокзал','11 маршрут', 1);
INSERT INTO transport_stop VALUES (377, 'ЖД.вокзал','на Азина', 1);
INSERT INTO transport_stop VALUES (378, 'Заводская','на Викулова', 1);
INSERT INTO transport_stop VALUES (379, 'Заводская','на Токарей', 1);
INSERT INTO transport_stop VALUES (380, 'Ильича','на м. пр. Космонавтов', 1);
INSERT INTO transport_stop VALUES (381, 'Ильича','Направление не указано', 1);
INSERT INTO transport_stop VALUES (382, 'Индустрии','на Ломоносова', 1);
INSERT INTO transport_stop VALUES (383, 'Индустрии','на Фрезеровщиков', 1);
INSERT INTO transport_stop VALUES (384, 'Индустрии','на Ильича', 1);
INSERT INTO transport_stop VALUES (385, 'Инженера Алиева','на Димитрова', 1);
INSERT INTO transport_stop VALUES (386, 'Инженера Алиева','на Нижнеисетск', 1);
INSERT INTO transport_stop VALUES (387, 'Инженерная','на Дагестанскую', 1);
INSERT INTO transport_stop VALUES (388, 'Инженерная','на Бородина', 1);
INSERT INTO transport_stop VALUES (389, 'Институт дерматологии','на Самолетную', 1);
INSERT INTO transport_stop VALUES (390, 'Институт дерматологии','на Гончарный', 1);
INSERT INTO transport_stop VALUES (391, 'Институт связи','на Токарей', 1);
INSERT INTO transport_stop VALUES (392, 'Институт связи','на Центральный стадион', 1);
INSERT INTO transport_stop VALUES (393, 'Институт связи','на Гурзуфскую', 1);
INSERT INTO transport_stop VALUES (394, 'Июльская','на Парковый пер.', 1);
INSERT INTO transport_stop VALUES (395, 'Июльская','на ст. Сулимова', 1);
INSERT INTO transport_stop VALUES (396, 'Калинина','на Победы', 1);
INSERT INTO transport_stop VALUES (397, 'Калинина','на Детскую больницу', 1);
INSERT INTO transport_stop VALUES (398, 'Калининская','на Педагогический университет', 1);
INSERT INTO transport_stop VALUES (399, 'Калининская','на Техучилище', 1);
INSERT INTO transport_stop VALUES (400, 'Каменный ручей','на Прониной', 1);
INSERT INTO transport_stop VALUES (401, 'Каменный ручей','на Уктус', 1);
INSERT INTO transport_stop VALUES (402, 'Карла Маркса','на Библиотеку им. Белинского', 1);
INSERT INTO transport_stop VALUES (403, 'Кварцевая','на ст. Табачная фабрика Альвис', 1);
INSERT INTO transport_stop VALUES (404, 'Кварцевая','на Павлодарскую', 1);
INSERT INTO transport_stop VALUES (405, 'Коммунистическая','Направление не указано', 1);
INSERT INTO transport_stop VALUES (406, 'Косарева','на ДК Химмаш', 1);
INSERT INTO transport_stop VALUES (407, 'Краснознаменная','на пл. 1-й Пятилетки', 1);
INSERT INTO transport_stop VALUES (408, 'Краснофлотцев','с Педагогического университета на м. Уралмаш', 1);
INSERT INTO transport_stop VALUES (409, 'Краснофлотцев','на Краснофлотцев', 1);
INSERT INTO transport_stop VALUES (410, 'Краснофлотцев','на Фронтовых Бригад', 1);
INSERT INTO transport_stop VALUES (411, 'Краснофлотцев','на Шефскую', 1);
INSERT INTO transport_stop VALUES (412, 'Красных Командиров','на ст. Таганская', 1);
INSERT INTO transport_stop VALUES (413, 'Красных Командиров','на Спортивную', 1);
INSERT INTO transport_stop VALUES (414, 'Крауля','на ст. Крауля', 1);
INSERT INTO transport_stop VALUES (415, 'Крауля','Направление не указано', 1);
INSERT INTO transport_stop VALUES (416, 'Крауля','на ст.Крауля(по требованию', 1);
INSERT INTO transport_stop VALUES (417, 'Крестинского','на Родонитовую', 1);
INSERT INTO transport_stop VALUES (418, 'Крестинского','на Шварца', 1);
INSERT INTO transport_stop VALUES (419, 'Куйбышева','на Карла Маркса', 1);
INSERT INTO transport_stop VALUES (420, 'Куйбышева','на Декабристов', 1);
INSERT INTO transport_stop VALUES (421, 'Лесная','на Рабочую', 1);
INSERT INTO transport_stop VALUES (422, 'Лесная','на ТК Академический', 1);
INSERT INTO transport_stop VALUES (423, 'Ломоносова','на Веер', 1);
INSERT INTO transport_stop VALUES (424, 'Ломоносова','на Индустрии', 1);
INSERT INTO transport_stop VALUES (425, 'Ломоносова','на Бакинских Комиссаров', 1);
INSERT INTO transport_stop VALUES (426, 'Ломоносова','на Восстания', 1);
INSERT INTO transport_stop VALUES (427, 'Луначарского','на ТЮЗ', 1);
INSERT INTO transport_stop VALUES (428, 'Луначарского','на Библиотеку им. Крапивина', 1);
INSERT INTO transport_stop VALUES (429, 'М. Динамо','на ТЮЗ', 1);
INSERT INTO transport_stop VALUES (430, 'М. Динамо','Направление не указано', 1);
INSERT INTO transport_stop VALUES (431, 'М. пр. Космонавтов','на Стахановскую', 1);
INSERT INTO transport_stop VALUES (432, 'М. пр. Космонавтов','на Старых Большевиков', 1);
INSERT INTO transport_stop VALUES (433, 'М. Уралмаш','на ст. пл. 1-й Пятилетки', 1);
INSERT INTO transport_stop VALUES (434, 'М. Уралмаш','на Педагогический университет', 1);
INSERT INTO transport_stop VALUES (435, 'М. Уралмаш','на ДК им. Лаврова', 1);
INSERT INTO transport_stop VALUES (436, 'Межевая','на Павлодарскую', 1);
INSERT INTO transport_stop VALUES (437, 'Менделеева','на Боровую', 1);
INSERT INTO transport_stop VALUES (438, 'Менделеева','на Парк Хаус', 1);
INSERT INTO transport_stop VALUES (439, 'Микрорайон','на ТК Академический', 1);
INSERT INTO transport_stop VALUES (440, 'Микрорайон','на ст. Академгородок', 1);
INSERT INTO transport_stop VALUES (441, 'Мира','на Уральский федеральный университет, Софьи Ковалевской', 1);
INSERT INTO transport_stop VALUES (442, 'Музей Бажова','на Трамвайный парк', 1);
INSERT INTO transport_stop VALUES (443, 'Начдива Онуфриева','на Академика Вонсовского', 1);
INSERT INTO transport_stop VALUES (444, 'Начдива Онуфриева','на Амундсена', 1);
INSERT INTO transport_stop VALUES (445, 'Начдива Онуфриева','на Чкалова', 1);
INSERT INTO transport_stop VALUES (446, 'Начдива Онуфриева','Направление не указано', 1);
INSERT INTO transport_stop VALUES (447, 'Нижнеисетск','на Инженера Алиева', 1);
INSERT INTO transport_stop VALUES (448, 'Нижнеисетск','на Опытную станцию садоводства', 1);
INSERT INTO transport_stop VALUES (449, 'Опытная станция садоводства','на Нижнеисетск', 1);
INSERT INTO transport_stop VALUES (450, 'Опытная станция садоводства','на Садовую', 1);
INSERT INTO transport_stop VALUES (451, 'Павлодарская','на Кварцевую', 1);
INSERT INTO transport_stop VALUES (452, 'Павлодарская','на Самолетную', 1);
INSERT INTO transport_stop VALUES (453, 'Парк Хаус','на Менделеева', 1);
INSERT INTO transport_stop VALUES (454, 'Парк Хаус','на Уральскую', 1);
INSERT INTO transport_stop VALUES (455, 'Парк Чкалова','на ст. Начдива Онуфриева', 1);
INSERT INTO transport_stop VALUES (456, 'Пархоменко','на Инженера Алиева', 1);
INSERT INTO transport_stop VALUES (457, 'Педагогический университет','Направление не указано', 1);
INSERT INTO transport_stop VALUES (458, 'Педагогический университет','на Краснофлотцев', 1);
INSERT INTO transport_stop VALUES (459, 'Педагогический университет','на Калининскую', 1);
INSERT INTO transport_stop VALUES (460, 'Пер. Парковый','на Июльскую', 1);
INSERT INTO transport_stop VALUES (461, 'Пер. Парковый','на Советскую', 1);
INSERT INTO transport_stop VALUES (462, 'Пер. Широкий','на Институт дерматологии', 1);
INSERT INTO transport_stop VALUES (463, 'Первомайская','на Студенческую', 1);
INSERT INTO transport_stop VALUES (464, 'Пионерская','на Уральскую', 1);
INSERT INTO transport_stop VALUES (465, 'Пионерская','на ЖД вокзал, 1-й км', 1);
INSERT INTO transport_stop VALUES (466, 'Пл. 1-й Пятилетки','Направление не указано', 1);
INSERT INTO transport_stop VALUES (467, 'Пл. 1-й Пятилетки','на Дом Пионеров', 1);
INSERT INTO transport_stop VALUES (468, 'Пл. 1-й Пятилетки','на Церковь Рождества Христова', 1);
INSERT INTO transport_stop VALUES (469, 'Победы','на Восстания', 1);
INSERT INTO transport_stop VALUES (470, 'Победы','на Калинина', 1);
INSERT INTO transport_stop VALUES (471, 'Посадская','Направление не указано', 1);
INSERT INTO transport_stop VALUES (472, 'Пр. Ленина','на Горького, Центральную гост.', 1);
INSERT INTO transport_stop VALUES (473, 'Пр. Ленина','на Архитектурную академию', 1);
INSERT INTO transport_stop VALUES (474, 'Пр. Орджоникидзе','на Калинина 8 м-т', 1);
INSERT INTO transport_stop VALUES (475, 'Пр. Орджоникидзе','на Калинина 10 м-т', 1);
INSERT INTO transport_stop VALUES (476, 'Пр-д Решетникова','на Чкалова', 1);
INSERT INTO transport_stop VALUES (477, 'Пр-д Решетникова','на Амундсена', 1);
INSERT INTO transport_stop VALUES (478, 'Прониной','на Артиллерийский институт', 1);
INSERT INTO transport_stop VALUES (479, 'Прониной','на Каменный ручей', 1);
INSERT INTO transport_stop VALUES (480, 'Профессорская','на Гагарина', 1);
INSERT INTO transport_stop VALUES (481, 'Профессорская','на Уральский федеральный университет', 1);
INSERT INTO transport_stop VALUES (482, 'Рабочая','на Лесную', 1);
INSERT INTO transport_stop VALUES (483, 'Рабочая','на Академика Вонсовского', 1);
INSERT INTO transport_stop VALUES (484, 'Репина','на Институт связи', 1);
INSERT INTO transport_stop VALUES (485, 'Родонитовая','на Тбилисский б-р', 1);
INSERT INTO transport_stop VALUES (486, 'Родонитовая','на Крестинского', 1);
INSERT INTO transport_stop VALUES (487, 'Рынок на Громова','на ст. Начдива Онуфриева', 1);
INSERT INTO transport_stop VALUES (488, 'Саввы Белых','на Авиационную', 1);
INSERT INTO transport_stop VALUES (489, 'Саввы Белых','на ст. Химмаш, ст. Ботаническая', 1);
INSERT INTO transport_stop VALUES (490, 'Садовая','на Опытную станцию садоводства', 1);
INSERT INTO transport_stop VALUES (491, 'Садовая','на Артиллерийский институт', 1);
INSERT INTO transport_stop VALUES (492, 'Самолетная','на Шварца', 1);
INSERT INTO transport_stop VALUES (493, 'Самолетная','на Межевую', 1);
INSERT INTO transport_stop VALUES (494, 'Самолетная','с Павлодарской на Самолетную', 1);
INSERT INTO transport_stop VALUES (495, 'Самолетная','на Институт дерматологии', 1);
INSERT INTO transport_stop VALUES (496, 'Серова','на Автовокзал', 1);
INSERT INTO transport_stop VALUES (497, 'Серова','на Шаумяна', 1);
INSERT INTO transport_stop VALUES (498, 'Советская','на пер. Парковый', 1);
INSERT INTO transport_stop VALUES (499, 'Советская','на Библиотеку им. Крапивина', 1);
INSERT INTO transport_stop VALUES (500, 'Софьи Ковалевской','на Первомайскую', 1);
INSERT INTO transport_stop VALUES (501, 'Спортивная','на Баумана', 1);
INSERT INTO transport_stop VALUES (502, 'Спортивная','на Шефскую', 1);
INSERT INTO transport_stop VALUES (503, 'Старых Большевиков','на Шефскую', 1);
INSERT INTO transport_stop VALUES (504, 'Стахановская','на Восстания', 1);
INSERT INTO transport_stop VALUES (505, 'Студенческая','на ст. Академическая', 1);
INSERT INTO transport_stop VALUES (506, 'Сулимова','Направление не указано', 1);
INSERT INTO transport_stop VALUES (507, 'Табачная фабрика','Направление не указано', 1);
INSERT INTO transport_stop VALUES (508, 'Таганская','на Шефскую', 1);
INSERT INTO transport_stop VALUES (509, 'Таганская','Направление не указано', 1);
INSERT INTO transport_stop VALUES (510, 'Тбилисский б-р','на б-р Малахова', 1);
INSERT INTO transport_stop VALUES (511, 'Тбилисский б-р','на Родонитовую', 1);
INSERT INTO transport_stop VALUES (512, 'Театр Волхонка','на ТЦ Алатырь', 1);
INSERT INTO transport_stop VALUES (513, 'Театр Волхонка','на Храм Большой Златоуст', 1);
INSERT INTO transport_stop VALUES (514, 'Техучилище','на Калининскую', 1);
INSERT INTO transport_stop VALUES (515, 'Техучилище','на 1-й км', 1);
INSERT INTO transport_stop VALUES (516, 'ТК Академический','на ст. Академгородок', 1);
INSERT INTO transport_stop VALUES (517, 'ТК Академический','на Лесную', 1);
INSERT INTO transport_stop VALUES (518, 'ТК Современник','на Академическую', 1);
INSERT INTO transport_stop VALUES (519, 'ТК Современник','на Данилы Зверева', 1);
INSERT INTO transport_stop VALUES (520, 'Токарей','на Заводскую', 1);
INSERT INTO transport_stop VALUES (521, 'Токарей','на Институт связи', 1);
INSERT INTO transport_stop VALUES (522, 'Трамвайный парк','на Фрунзе', 1);
INSERT INTO transport_stop VALUES (523, 'Трансагентство','на Дом Кино', 1);
INSERT INTO transport_stop VALUES (524, 'Трансагентство','на Генеральскую', 1);
INSERT INTO transport_stop VALUES (525, 'ТЦ Алатырь','на Центральный стадион', 1);
INSERT INTO transport_stop VALUES (526, 'ТЦ Алатырь','на Театр Волхонка', 1);
INSERT INTO transport_stop VALUES (527, 'ТЮЗ','с Архитектурной академии на Дом Музыки', 1);
INSERT INTO transport_stop VALUES (528, 'ТЮЗ','на Архитектурную академию', 1);
INSERT INTO transport_stop VALUES (529, 'ТЮЗ','на ст. м. Динамо', 1);
INSERT INTO transport_stop VALUES (530, 'ТЮЗ','со ст. м. Динамо на Луначарского', 1);
INSERT INTO transport_stop VALUES (531, 'Уктус','на Гончарный', 1);
INSERT INTO transport_stop VALUES (532, 'Уктус','на Каменный ручей', 1);
INSERT INTO transport_stop VALUES (533, 'Уктус','Направление не указано', 1);
INSERT INTO transport_stop VALUES (534, 'Уральская','на Парк Хаус', 1);
INSERT INTO transport_stop VALUES (535, 'Уральская','на Пионерскую', 1);
INSERT INTO transport_stop VALUES (536, 'Уральский федеральный университет','на Профессорскую', 1);
INSERT INTO transport_stop VALUES (537, 'Уральский федеральный университет','на Софьи Ковалевской', 1);
INSERT INTO transport_stop VALUES (538, 'Федерация профсоюзов','на Куйбышева', 1);
INSERT INTO transport_stop VALUES (539, 'Фрезеровщиков','на Индустрии', 1);
INSERT INTO transport_stop VALUES (540, 'Фрезеровщиков','на ДК им. Лаврова', 1);
INSERT INTO transport_stop VALUES (541, 'Фрезеровщиков','с Шефской на м. пр. Космонавтов', 1);
INSERT INTO transport_stop VALUES (542, 'Фронтовых Бригад','на Краснофлотцев', 1);
INSERT INTO transport_stop VALUES (543, 'Фронтовых Бригад','на Ворошиловскую', 1);
INSERT INTO transport_stop VALUES (544, 'Фрунзе','на Щорса', 1);
INSERT INTO transport_stop VALUES (545, 'Фрунзе','на Большакова', 1);
INSERT INTO transport_stop VALUES (546, 'Химмаш','Направление не указано', 1);
INSERT INTO transport_stop VALUES (547, 'Хмелева','на б-р Культуры', 1);
INSERT INTO transport_stop VALUES (548, 'Храм Большой Златоуст','на Театр Волхонка', 1);
INSERT INTO transport_stop VALUES (549, 'Храм Большой Златоуст','на Центральную гост.', 1);
INSERT INTO transport_stop VALUES (550, 'Центральная гост.','на пр. Ленина, Дом Кино', 1);
INSERT INTO transport_stop VALUES (551, 'Центральная гост.','на Федерацию профсоюзов, Библиотеку им. Белинского', 1);
INSERT INTO transport_stop VALUES (552, 'Центральный стадион','на Институт связи', 1);
INSERT INTO transport_stop VALUES (553, 'Центральный стадион','на ТЦ Алатырь', 1);
INSERT INTO transport_stop VALUES (554, 'Церковь Рождества Христова','на 40 лет Октября', 1);
INSERT INTO transport_stop VALUES (555, 'ЦПКиО','Направление не указано', 1);
INSERT INTO transport_stop VALUES (556, 'Чапаева','на Музей Бажова', 1);
INSERT INTO transport_stop VALUES (557, 'Чкалова','на парк Чкалова', 1);
INSERT INTO transport_stop VALUES (558, 'Чкалова','на пр-д Решетникова', 1);
INSERT INTO transport_stop VALUES (559, 'Шаумяна','на Волгоградскую', 1);
INSERT INTO transport_stop VALUES (560, 'Шаумяна','на Серова', 1);
INSERT INTO transport_stop VALUES (561, 'Шварца','на Самолетную', 1);
INSERT INTO transport_stop VALUES (562, 'Шварца','на Саввы Белых', 1);
INSERT INTO transport_stop VALUES (563, 'Шефская','с Таганской на Фрезеровщиков', 1);
INSERT INTO transport_stop VALUES (564, 'Шефская','со Старых Большевиков на ст. Таганская', 1);
INSERT INTO transport_stop VALUES (565, 'Шефская','с Краснофлотцев на Спортивную', 1);
INSERT INTO transport_stop VALUES (566, 'Шефская','со Спортивной на Краснофлотцев', 1);
INSERT INTO transport_stop VALUES (567, 'Школа','на Библиотеку', 1);
INSERT INTO transport_stop VALUES (568, 'Щербакова','на ТРЦ Екатерининский', 1);
INSERT INTO transport_stop VALUES (569, 'Щорса','на Авиационную', 1);
INSERT INTO transport_stop VALUES (570, 'Щорса','на Фрунзе', 1);
INSERT INTO transport_stop VALUES (571, 'Щорса','на Автовокзал', 1);
INSERT INTO transport_stop VALUES (572, 'Щорса','на ст. ЦПКиО', 1);
INSERT INTO transport_stop VALUES (573, 'Электриков','на Ворошиловскую', 1);
INSERT INTO transport_stop VALUES (574, 'Электриков','на ст. Педагогический университет', 1);
INSERT INTO transport_stop VALUES (575, 'Южный пр.','на ст. Табачная фабрика', 1);
INSERT INTO transport_stop VALUES (576, 'Южный пр.','на Кварцевую', 1);
INSERT INTO transport_stop VALUES (577, 'Ярославская','на ст. Коммунистическая', 1);
INSERT INTO transport_stop VALUES (578, 'Ярославская','на Веер', 1);
INSERT INTO transport_stop VALUES (579, '1-й км','на Пионерскую', 0);
INSERT INTO transport_stop VALUES (580, '1-й км','на Техучилище', 0);
INSERT INTO transport_stop VALUES (581, '1-й км','на Техучилище', 1);
INSERT INTO transport_stop VALUES (582, '1-й км','на Ж/д вокзал, Пионерскую', 1);